### ISSUE TITLE
Update to support net5.0 -  I have a branch ready to be pushed if you will allow me to do so.

### ISSUE THREAD

**Issue by fridayhut** [gabrielweyer/xunit-to-junit#4]

**Comment by gabrielweyer** [comment]
Sure, please create a Pull Request.

Please note that we need to continue supporting `netcoreapp2.1` and `netcoreapp3.1` as some developers have not migrated to .NET 5 yet.

**Comment by fridayhut** [comment]
Hi,

I think you will need to add me as a contributor to be able to push a pull
request. I tried to push the branch and it failed with a permissions error.

Cheers
Dan.

**Comment by gabrielweyer** [comment]
You'll need to fork this repository first. GitHub has a [guide](https://guides.github.com/activities/forking/) on how to fork a repository and create a Pull Request.

**Comment by fridayhut** [comment]
Thanks, I'll check it out.
