### ISSUE TITLE
Output Junit file doesn't have test name for a test case

### ISSUE THREAD

**Issue by RohitVegesna** [gabrielweyer/xunit-to-junit#7]
Hey, 
Thanks for developing this nice tool which helps in uploading test results in CircleCI. 
We tried to use this package and upload test results in circleCI run but looks like we have no test case name shown both in ran pipeline and circleCI insights. When looking further into resulted JUnit file, found that there is a test case name printed which we have in the source file (xunit result).

Attaching our sample snipptes of both xunit_result.xml and junit_result.xml (which was generated using this nuget)
Snippet of Xunit_result.xml
![image](https://user-images.githubusercontent.com/75778145/140911791-754305d7-28e6-42e2-9f5c-bb77321296bc.png)

Snippet of resulting file (junit)
![image](https://user-images.githubusercontent.com/75778145/140911852-0dd06a6a-3b08-48a7-8542-7382d4e68095.png)
In the above snippet, test case name is blank.

We are using 'XunitXml.TestLogger' nuget to generate the xunit result XML.
Could you please guide us on how to resolve this, without the test name in the JUnit file, circleCI shows blank rows under the test case name column.
Your response is highly appreciated !!

Thanks in advance.

**Comment by gabrielweyer** [comment]
Hey @RohitVegesna could you please attach the `Xunit_result.xml` file to this issue? It looks like it was created specifically to reproduce the issue you reported and so should no contain any sensitive data.

**Comment by RohitVegesna** [comment]
Hey @gabrielweyer,
Thanks for getting back !!
I have now created a sample project and generated Xunit_result.xml and used xunit-to-junit nuget to convert to junit_result,XML.
Attaching both files in a single compressed file.
[Xunit and Junit xmls.zip](https://github.com/gabrielweyer/xunit-to-junit/files/7512506/Xunit.and.Junit.xmls.zip)

Please let me know if you require any more info to troubleshoot the issue.

Thanks

**Comment by gabrielweyer** [comment]
I assume you provided a value to `DisplayName`?

```csharp
[Fact(DisplayName = "Ignoring scenario")]
```

I published [v3.0.0](https://www.nuget.org/packages/dotnet-xunit-to-junit/3.0.0) on NuGet moments ago. Please let me know if it doesn't solve your issue.

**Comment by RohitVegesna** [comment]
@gabrielweyer With the new version. I am able to see the name in the converted file. 
Thanks for resolving it !!
